language: node_js
node_js:
  - "0.12"
git:
    submodules: false
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
	- npm install -g grunt-cli
install: npm install
before_script: grunt